export const userActionTypes = {
  GET_USER_LIST_LOADING: 'GET_USER_LIST_LOADING',
  GET_USER_LIST_SUCCESS: 'GET_USER_LIST_SUCCESS',
  GET_USER_LIST_ERROR: 'GET_USER_LIST_ERROR',
  UPDATE_USER_LOADING: 'UPDATE_USER_LOADING',
  UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
  UPDATE_USER_ERROR: 'UPDATE_USER_ERROR',
  INVITE_USER_LOADING: 'INVITE_USER_LOADING',
  INVITE_USER_SUCCESS: 'INVITE_USER_SUCCESS',
  INVITE_USER_ERROR: 'INVITE_USER_ERROR',
  DELETE_USER_LOADING: 'DELETE_USER_LOADING',
  DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
};
