/* eslint-disable import/prefer-default-export */
import { AnimalTableData } from './FtrAnimals.types';

export const animalMock: AnimalTableData[] = [
  {
    key: 1,
    id: 1,
    tenantId: 1101010,
    name: 'Agatha',
    type: 'Parrot',
    breed: 'Macaw',
    color: '',
    gender: '',
    birthday: '4/30/2015',
    location: '',
    isFlagged: true,
    flag: 'Some reason',
    isSpayedNeutered: false,
    Story: '',
    note: '',
    profilePhotoUrl: '',
    intakeDate: '',
    acquiredHow: '',
    amountPaid: 0,
    amountReceived: 0,
    intakeNote: '',
    resident: 'current',
  },
  {
    key: 2,
    id: 2,
    tenantId: 1101010,
    name: 'Bentley',
    type: 'Rabbit',
    breed: 'English Lop',
    color: '',
    gender: '',
    birthday: '4/30/2019',
    location: '',
    isFlagged: false,
    flag: '',
    isSpayedNeutered: false,
    Story: '',
    note: '',
    profilePhotoUrl: '',
    intakeDate: '',
    acquiredHow: '',
    amountPaid: 0,
    amountReceived: 0,
    intakeNote: '',
    resident: 'current',
  },
  {
    key: 3,
    id: 3,
    tenantId: 1101010,
    name: 'Bo',
    type: 'Dog',
    breed: 'Shih Tzu',
    color: '',
    gender: '',
    birthday: '4/29/2016',
    location: '',
    isFlagged: false,
    flag: '',
    isSpayedNeutered: false,
    Story: '',
    note: '',
    profilePhotoUrl: '',
    intakeDate: '',
    acquiredHow: '',
    amountPaid: 0,
    amountReceived: 0,
    intakeNote: '',
    resident: 'former',
  },
  {
    key: 4,
    id: 4,
    tenantId: 1101010,
    name: 'Maple',
    type: 'Dog',
    breed: 'Doberman',
    color: '',
    gender: '',
    birthday: '4/21/2018',
    location: '',
    isFlagged: false,
    flag: '',
    isSpayedNeutered: false,
    Story: '',
    note: '',
    profilePhotoUrl: '',
    intakeDate: '',
    acquiredHow: '',
    amountPaid: 0,
    amountReceived: 0,
    intakeNote: '',
    resident: 'current',
  },
  {
    key: 5,
    id: 5,
    tenantId: 1101010,
    name: 'Casper',
    type: 'Dog',
    breed: 'Doberman',
    color: '',
    gender: '',
    birthday: '4/21/2018',
    location: '',
    isFlagged: false,
    flag: '',
    isSpayedNeutered: false,
    Story: '',
    note: '',
    profilePhotoUrl: '',
    intakeDate: '',
    acquiredHow: '',
    amountPaid: 0,
    amountReceived: 0,
    intakeNote: '',
    resident: 'current',
  },
  {
    key: 6,
    id: 6,
    tenantId: 1101010,
    name: 'Dusty',
    type: 'Dog',
    breed: 'Doberman',
    color: '',
    gender: '',
    birthday: '4/21/2018',
    location: '',
    isFlagged: false,
    flag: '',
    isSpayedNeutered: false,
    Story: '',
    note: '',
    profilePhotoUrl: '',
    intakeDate: '',
    acquiredHow: '',
    amountPaid: 0,
    amountReceived: 0,
    intakeNote: '',
    resident: 'current',
  },
  {
    key: 7,
    id: 7,
    tenantId: 1101010,
    name: 'Ingrid',
    type: 'Dog',
    breed: 'Doberman',
    color: '',
    gender: '',
    birthday: '4/21/2018',
    location: '',
    isFlagged: false,
    flag: '',
    isSpayedNeutered: false,
    Story: '',
    note: '',
    profilePhotoUrl: '',
    intakeDate: '',
    acquiredHow: '',
    amountPaid: 0,
    amountReceived: 0,
    intakeNote: '',
    resident: 'current',
  },
  {
    key: 8,
    id: 8,
    tenantId: 1101010,
    name: 'Honey',
    type: 'Dog',
    breed: 'Doberman',
    color: '',
    gender: '',
    birthday: '4/21/2018',
    location: '',
    isFlagged: false,
    flag: '',
    isSpayedNeutered: false,
    Story: '',
    note: '',
    profilePhotoUrl: '',
    intakeDate: '',
    acquiredHow: '',
    amountPaid: 0,
    amountReceived: 0,
    intakeNote: '',
    resident: 'current',
  },
  {
    key: 9,
    id: 9,
    tenantId: 1101010,
    name: 'Milo',
    type: 'Dog',
    breed: 'Doberman',
    color: '',
    gender: '',
    birthday: '4/21/2018',
    location: '',
    isFlagged: false,
    flag: '',
    isSpayedNeutered: false,
    Story: '',
    note: '',
    profilePhotoUrl: '',
    intakeDate: '',
    acquiredHow: '',
    amountPaid: 0,
    amountReceived: 0,
    intakeNote: '',
    resident: 'current',
  },
  {
    key: 10,
    id: 10,
    tenantId: 1101010,
    name: 'Mikey',
    type: 'Dog',
    breed: 'Doberman',
    color: '',
    gender: '',
    birthday: '4/21/2018',
    location: '',
    isFlagged: false,
    flag: '',
    isSpayedNeutered: false,
    Story: '',
    note: '',
    profilePhotoUrl: '',
    intakeDate: '',
    acquiredHow: '',
    amountPaid: 0,
    amountReceived: 0,
    intakeNote: '',
    resident: 'current',
  },
  {
    key: 11,
    id: 11,
    tenantId: 1101010,
    name: 'Nick',
    type: 'Dog',
    breed: 'Doberman',
    color: '',
    gender: '',
    birthday: '4/21/2018',
    location: '',
    isFlagged: false,
    flag: '',
    isSpayedNeutered: false,
    Story: '',
    note: '',
    profilePhotoUrl: '',
    intakeDate: '',
    acquiredHow: '',
    amountPaid: 0,
    amountReceived: 0,
    intakeNote: '',
    resident: 'current',
  },
  {
    key: 12,
    id: 12,
    tenantId: 1101010,
    name: 'Pinot',
    type: 'Dog',
    breed: 'Doberman',
    color: '',
    gender: '',
    birthday: '4/21/2018',
    location: '',
    isFlagged: false,
    flag: '',
    isSpayedNeutered: false,
    Story: '',
    note: '',
    profilePhotoUrl: '',
    intakeDate: '',
    acquiredHow: '',
    amountPaid: 0,
    amountReceived: 0,
    intakeNote: '',
    resident: 'current',
  },
];
