export const pcoActionTypes = {
  GET_PCO_LIST_LOADING: 'GET_PCO_LIST_LOADING',
  GET_PCO_LIST_SUCCESS: 'GET_PCO_LIST_SUCCESS',
  GET_PCO_LIST_ERROR: 'GET_PCO_LIST_ERROR',
  ADD_PCO_LOADING: 'ADD_PCO_LOADING',
  ADD_PCO_SUCCESS: 'ADD_PCO_SUCCESS',
  SET_SELECTED_PCO: 'SET_SELECTED_PCO',
  UPDATE_PCO_LOADING: 'UPDATE_PCO_LOADING',
  UPDATE_PCO_SUCCESS: 'UPDATE_PCO_SUCCESS',
  DELETE_PCO_SUCCESS: 'DELETE_PCO_SUCCESS',
  DELETE_PCO_LOADING: 'DELETE_PCO_LOADING',
  GET_PCO_SUGGESTION_LIST_LOADING: 'GET_PCO_SUGGESTION_LIST_LOADING',
  GET_PCO_SUGGESTION_LIST_SUCCESS: 'GET_PCO_SUGGESTION_LIST_SUCCESS',
};
