export const commonActionTypes = {
  GET_COUNT_LOADING: 'GET_COUNT_LOADING',
  GET_COUNT_SUCCESS: 'GET_COUNT_SUCCESS',
  GET_COUNT_ERROR: 'GET_COUNT_ERROR',
  UPLOAD_IMAGE_LOADING: 'UPLOAD_IMAGE_LOADING',
  UPLOAD_IMAGE_SUCCESS: 'UPLOAD_IMAGE_SUCCESS',
  DELETE_IMAGE_LOADING: 'DELETE_IMAGE_LOADING',
  DELETE_IMAGE_SUCCESS: 'DELETE_IMAGE_SUCCESS',
};
